version: '3.8'

networks:
  warcraft-network:
    driver: bridge

volumes:
  user-db-data:
    driver: local
  redis-data:

services:
  # --- Сервис пользователей ---
  user-service:
    build:
      context: .
      dockerfile: ./apps/api/services/user-service/Dockerfile
    container_name: warcraft-user-service
    restart: unless-stopped
    environment:
      DATABASE_URL: ${USER_DB_URL}
      PORT: ${USER_SERVICE_INTERNAL_PORT:-3000}
    ports:
      - '${USER_SERVICE_EXTERNAL_PORT:-3001}:${USER_SERVICE_INTERNAL_PORT:-3000}'
    depends_on:
      - user-db
    networks:
      - warcraft-network

  # --- База данных для сервиса пользователей ---
  user-db:
    image: postgres:16
    container_name: nexus-user-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - '${USER_DB_EXTERNAL_PORT}:5432'
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - warcraft-network

  redis:
    image: redis:alpine
    container_name: nexus-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - warcraft-network
